INSERT INTO INCOMES (ID, CHAT_ID, INCOME) VALUES (DEFAULT, 2, 3000)
INSERT INTO INCOMES (ID, CHAT_ID, INCOME) VALUES (DEFAULT, 3, 5000)
INSERT INTO INCOMES (ID, CHAT_ID, INCOME) VALUES (DEFAULT, 5, 10000)

INSERT INTO SPEND (ID, CHAT_ID, SPEND) VALUES (DEFAULT, 5, 10000)
INSERT INTO SPEND (ID, CHAT_ID, SPEND) VALUES (DEFAULT, 10, 100000)